import { createClient } from '@/lib/supabase/client'
import type { ServiceOrder, CreateOrderDto, UpdateOrderDto } from '../types/order.types'

export const orderService = {
  /**
   * Get all service orders for current tenant
   */
  async getOrders(): Promise<ServiceOrder[]> {
    const supabase = createClient()
    
    const { data, error } = await supabase
      .from('service_orders')
      .select(`
        *,
        client:clients(id, name, phone, email),
        assigned_technician:profiles!assigned_to(id, full_name)
      `)
      .order('created_at', { ascending: false })
    
    if (error) throw error
    return data as ServiceOrder[]
  },

  /**
   * Get order by ID
   */
  async getOrderById(id: string): Promise<ServiceOrder> {
    const supabase = createClient()
    
    const { data, error } = await supabase
      .from('service_orders')
      .select(`
        *,
        client:clients(id, name, phone, email, address),
        assigned_technician:profiles!assigned_to(id, full_name)
      `)
      .eq('id', id)
      .single()
    
    if (error) throw error
    return data as ServiceOrder
  },

  /**
   * Get orders by status
   */
  async getOrdersByStatus(status: string): Promise<ServiceOrder[]> {
    const supabase = createClient()
    
    const { data, error } = await supabase
      .from('service_orders')
      .select(`
        *,
        client:clients(id, name, phone, email),
        assigned_technician:profiles!assigned_to(id, full_name)
      `)
      .eq('status', status)
      .order('created_at', { ascending: false })
    
    if (error) throw error
    return data as ServiceOrder[]
  },

  /**
   * Create new service order
   */
  async createOrder(dto: CreateOrderDto): Promise<ServiceOrder> {
    const supabase = createClient()
    
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) throw new Error('Not authenticated')
    
    const { data: profile } = await supabase
      .from('profiles')
      .select('active_tenant_id')
      .eq('id', user.id)
      .single()
    
    if (!profile?.active_tenant_id) throw new Error('No active tenant')
    
    const insertData = {
      tenant_id: profile.active_tenant_id,
      client_id: dto.clientId,
      order_type: dto.orderType,
      priority: dto.priority,
      service_title: dto.serviceTitle,
      service_description: dto.serviceDescription,
      location_address: dto.locationAddress,
      requested_date: dto.requestedDate?.toISOString().split('T')[0],
      estimated_duration: dto.estimatedDuration,
      notes: dto.notes,
      created_by: user.id,
      order_number: '', // Will be auto-generated by trigger
    }
    
    const { data, error } = await supabase
      .from('service_orders')
      .insert(insertData)
      .select(`
        *,
        client:clients(id, name, phone, email)
      `)
      .single()
    
    if (error) throw error
    return data as ServiceOrder
  },

  /**
   * Update service order
   */
  async updateOrder(id: string, dto: UpdateOrderDto): Promise<ServiceOrder> {
    const supabase = createClient()
    
    const { data, error } = await supabase
      .from('service_orders')
      .update(dto)
      .eq('id', id)
      .select(`
        *,
        client:clients(id, name, phone, email),
        assigned_technician:profiles!assigned_to(id, full_name)
      `)
      .single()
    
    if (error) throw error
    return data as ServiceOrder
  },

  /**
   * Delete service order
   */
  async deleteOrder(id: string): Promise<void> {
    const supabase = createClient()
    
    const { error } = await supabase
      .from('service_orders')
      .delete()
      .eq('id', id)
    
    if (error) throw error
  },

  /**
   * Assign technician to order
   */
  async assignTechnician(orderId: string, technicianId: string): Promise<ServiceOrder> {
    return this.updateOrder(orderId, {
      assigned_to: technicianId,
      status: 'scheduled',
    })
  },

  /**
   * Update order status
   */
  async updateStatus(orderId: string, status: string): Promise<ServiceOrder> {
    return this.updateOrder(orderId, { status: status as any })
  },
}
